package component:nfs-rs

world nfs-rs {
    import wasi:poll/poll
    import wasi:io/streams
    import wasi:sockets/network
    import wasi:sockets/ip-name-lookup
    import wasi:sockets/tcp
    import wasi:sockets/tcp-create-socket
    export nfs
}
